services:
  - type: web
    name: vhu-telegram-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7515936236:AAEkHwK2dIzgVfYZY9ZTN7lNl2mfB5IolFM # Cập nhật token của cậu
      - key: VHU_EMAIL
        value: 221A010032 # Cập nhật email của cậu
      - key: VHU_PASSWORD
        value: 0411Vcc. # Cập nhật mật khẩu của cậu
    healthCheckPath: /ping
    autoDeploy: true
    port: 10000