services:
  - type: web
    name: vhu-telegram-bot-new
    env: docker # Sử dụng Docker thay vì Node
    plan: free
    buildCommand: "" # Không cần buildCommand vì Dockerfile sẽ xử lý
    startCommand: "" # Không cần startCommand vì Dockerfile đã định nghĩa CMD
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7515936236:AAEkHwK2dIzgVfYZY9ZTN7lNl2mfB5IolFM
      - key: VHU_EMAIL
        value: 221A010032
      - key: VHU_PASSWORD
        value: 0411Vcc.
      - key: PORT
        value: 10000
      - key: CHROME_PATH
        value: /usr/bin/google-chrome-stable
    healthCheckPath: /ping
    autoDeploy: true
    dockerfilePath: Dockerfile # Chỉ định rõ Dockerfile