services:
  - type: web
    name: vhu-telegram-bot-new
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7515936236:AAEkHwK2dIzgVfYZY9ZTN7lNl2mfB5IolFM
      - key: VHU_EMAIL
        value: 221A010032
      - key: VHU_PASSWORD
        value: 0411Vcc.
      - key: PORT
        value: 10000
      - key: CHROME_PATH
        value: /usr/bin/chromium
    healthCheckPath: /ping
    autoDeploy: true
    dockerfilePath: Dockerfile